namespace CodeyBox.Core;

/// <summary>
/// A question emitted by an agent mid-work, awaiting an operator answer.
/// Questions are scoped to a work item and identified by an agent-supplied
/// stable ID (e.g. "q-001"). Duplicate (workItemId, questionId) pairs are
/// ignored — agents may re-emit on every iteration.
/// </summary>
public sealed record WorkItemQuestion
{
    /// <summary>Primary key — internal UUID generated by the orchestrator.</summary>
    public required string Id { get; init; }

    /// <summary>The work item this question belongs to.</summary>
    public required string WorkItemId { get; init; }

    /// <summary>Agent-supplied stable question identifier (e.g. "q-001").</summary>
    public required string QuestionId { get; init; }

    /// <summary>The question text, redacted of any detected secrets.</summary>
    public required string QuestionText { get; init; }

    public DateTimeOffset AskedAt { get; init; } = DateTimeOffset.UtcNow;
    public DateTimeOffset? AnsweredAt { get; init; }
    public string? AnswerText { get; init; }
    public string? AnsweredBy { get; init; }
    public DateTimeOffset? DismissedAt { get; init; }
    public string? DismissReason { get; init; }

    /// <summary>Lifecycle state: "open", "answered", or "dismissed".</summary>
    public string State { get; init; } = "open";
}
