#!/usr/bin/env bash
#
# setup-host-networks.sh — operator-run setup for CodeyBox per-VM egress
# enforcement on Multipass-based sandboxes.
#
# What this does:
#   1. For each profile in the config file, creates a Linux bridge
#      (via systemd-networkd) with its own subnet and built-in DHCP server.
#   2. Writes nftables rules that:
#        - block all forward traffic on Multipass's default mpqemubr0
#          (so the VM's default NIC has no internet path)
#        - apply per-bridge allowlists (loopback, ESTABLISHED/RELATED, DNS,
#          and the resolved IPs of the configured allowed hosts; everything
#          else dropped)
#   3. Persists the rules so they survive reboot.
#
# Why: enforcement HAS to live on the host. An agent inside a VM with sudo
# can flush in-VM iptables, but it cannot touch the host's forward chain.
#
# Usage:
#   sudo /path/to/setup-host-networks.sh [config-file]
#
# If no config file is given, /etc/codeybox/networks.conf is used. Format:
# one profile per line, columns separated by whitespace —
#
#   # name           bridge          subnet         allowed-hosts
#   isolated         cb-iso          10.99.1.0/24   -
#   claude           cb-claude       10.99.2.0/24   api.anthropic.com
#   codex            cb-codex        10.99.3.0/24   api.openai.com
#   multi-llm        cb-multi-llm    10.99.4.0/24   api.anthropic.com,api.openai.com,api.githubcopilot.com
#   internet-only    cb-net          10.99.5.0/24   internet
#   graphical        cb-graphical    10.99.6.0/24   internet
#
# allowed-hosts column accepts:
#   "-"                     — no egress (only DNS + loopback + replies)
#   "internet"              — full public internet, but block RFC1918 /
#                             link-local / cloud-metadata / multicast etc.
#                             Useful for "wide reach but no LAN attacks."
#   "host1,host2,…"         — comma-separated hostname allowlist (current
#                             list is resolved to IPs at setup time)
#
# Bridge names (column 2) must be ≤15 chars (Linux IFNAMSIZ limit).
# Profile names (column 1) have no length limit.
#
# Idempotent — re-run after editing the config or to refresh resolved IPs
# (useful when CDN endpoints rotate).

set -euo pipefail

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
    echo "must be run as root (try: sudo $0 $*)" >&2
    exit 1
fi

CONFIG_FILE="${1:-/etc/codeybox/networks.conf}"
NFT_FILE="/etc/nftables.d/codeybox.nft"
NETWORKD_DIR="/etc/systemd/network"
MULTIPASS_DEFAULT_IFACE="${CODEYBOX_MULTIPASS_DEFAULT_IFACE:-mpqemubr0}"
VNC_HELPER="/usr/local/bin/codeybox-vnc-loopback"

if [[ ! -r "$CONFIG_FILE" ]]; then
    cat >&2 <<EOF
config file $CONFIG_FILE not found.

Create it as: <name> <bridge> <subnet> <allowed-hosts-comma-sep-or-dash>

Example:
  # name           bridge          subnet         allowed-hosts
  isolated         cb-iso          10.99.1.0/24   -
  claude           cb-claude       10.99.2.0/24   api.anthropic.com
  graphical        cb-graphical    10.99.6.0/24   internet

Then re-run: sudo $0 [path/to/config]
EOF
    exit 1
fi

# Sanity-check tooling.
for cmd in nft ip systemctl getent; do
    command -v "$cmd" >/dev/null 2>&1 || { echo "missing required tool: $cmd" >&2; exit 1; }
done
mkdir -p "$NETWORKD_DIR" "$(dirname "$NFT_FILE")"

# ---------------------------------------------------------------------------
# Parse the config file.
# ---------------------------------------------------------------------------
declare -a NAMES BRIDGES SUBNETS HOSTS
while IFS= read -r raw; do
    # Strip comments and surrounding whitespace.
    line="${raw%%#*}"
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" ]] && continue

    # Expect 4 whitespace-separated columns.
    read -r name bridge subnet hosts _rest <<< "$line"
    if [[ -z "$name" || -z "$bridge" || -z "$subnet" || -z "$hosts" ]]; then
        echo "invalid line: $raw" >&2; exit 1
    fi
    NAMES+=("$name"); BRIDGES+=("$bridge"); SUBNETS+=("$subnet"); HOSTS+=("$hosts")
done < "$CONFIG_FILE"

if [[ ${#NAMES[@]} -eq 0 ]]; then
    echo "no profiles in $CONFIG_FILE" >&2; exit 1
fi

# ---------------------------------------------------------------------------
# Per-profile systemd-networkd configuration: bridge + DHCPv4 server.
# ---------------------------------------------------------------------------
for i in "${!NAMES[@]}"; do
    bridge="${BRIDGES[$i]}"
    subnet="${SUBNETS[$i]}"
    network="${subnet%/*}"
    prefix="${subnet#*/}"
    # Gateway: x.y.z.1
    gw="$(awk -F. -v OFS=. '{print $1,$2,$3,1}' <<< "$network")"

    cat > "$NETWORKD_DIR/10-${bridge}.netdev" <<EOF
# Generated by codeybox setup-host-networks.sh — do not edit by hand.
[NetDev]
Name=${bridge}
Kind=bridge
EOF

    cat > "$NETWORKD_DIR/10-${bridge}.network" <<EOF
# Generated by codeybox setup-host-networks.sh — do not edit by hand.
[Match]
Name=${bridge}

[Network]
Address=${gw}/${prefix}
ConfigureWithoutCarrier=yes
DHCPServer=yes
IPMasquerade=ipv4

[DHCPServer]
PoolOffset=10
PoolSize=200
EmitDNS=yes
DNS=1.1.1.1
EOF
done

# ---------------------------------------------------------------------------
# Build the nftables ruleset.
# ---------------------------------------------------------------------------
ts="$(date -Iseconds)"

{
cat <<EOF
# Generated by codeybox setup-host-networks.sh at ${ts}.
# Do not edit by hand — re-run the script to regenerate.

table inet codeybox {
    chain forward {
        type filter hook forward priority -10; policy accept;

        # Multipass's default bridge — drop ALL forwarded traffic. The
        # multipass control plane uses INPUT (host -> guest), not FORWARD,
        # so this doesn't break VM management.
        iifname "${MULTIPASS_DEFAULT_IFACE}" jump cb-default-blocked
        oifname "${MULTIPASS_DEFAULT_IFACE}" jump cb-default-blocked
EOF

for i in "${!NAMES[@]}"; do
    name="${NAMES[$i]}"
    bridge="${BRIDGES[$i]}"
    echo "        iifname \"${bridge}\" jump cb-${name}"
    echo "        oifname \"${bridge}\" jump cb-${name}-in"
done

cat <<EOF
    }

    chain cb-default-blocked {
        # Multipass's default mpqemubr0 has no useful internet path. Drop.
        drop
    }
EOF

for i in "${!NAMES[@]}"; do
    name="${NAMES[$i]}"
    hosts="${HOSTS[$i]}"

    cat <<EOF

    chain cb-${name}-in {
        # Block LAN-forwarded inbound traffic to sandbox bridges. Host-originated
        # connections (including operator-managed 127.0.0.1 tunnels for VNC)
        # do not traverse this forward chain, and established replies remain
        # allowed so VM-initiated connections continue to work.
        ct state established,related accept
        drop
    }

    chain cb-${name} {
        # Standard "allow replies + DNS" preamble.
        ct state established,related accept
        ip protocol icmp accept
        udp dport 53 accept
        tcp dport 53 accept
EOF

    if [[ "$hosts" == "internet" ]]; then
        # Internet-only mode: drop all LAN/private/local destinations,
        # accept public internet. Useful when you want to give the agent
        # broad reach (any external API) while preventing it from being a
        # staging ground for attacks against the local network.
        #
        # Forward-chain semantics: only forwarded packets hit these rules.
        # The bridge's own traffic (VM <-> bridge gateway, VM <-> VM on the
        # same bridge) goes through L2 and never reaches forward, so
        # dropping 10.0.0.0/8 here doesn't break the VM's connectivity to
        # the bridge gateway it's actually using (10.99.x.1).
        cat <<'INNER'
        # IPv4 LAN / private / local / metadata-service ranges — drop.
        ip daddr 10.0.0.0/8 drop          comment "RFC1918 / multipass private"
        ip daddr 172.16.0.0/12 drop       comment "RFC1918"
        ip daddr 192.168.0.0/16 drop      comment "RFC1918"
        ip daddr 100.64.0.0/10 drop       comment "CGNAT"
        ip daddr 169.254.0.0/16 drop      comment "link-local + cloud metadata (169.254.169.254)"
        ip daddr 127.0.0.0/8 drop         comment "loopback"
        ip daddr 224.0.0.0/4 drop         comment "multicast"
        ip daddr 240.0.0.0/4 drop         comment "reserved"
        # IPv6 LAN / private / local — drop.
        ip6 daddr fc00::/7 drop           comment "ULA"
        ip6 daddr fe80::/10 drop          comment "link-local"
        ip6 daddr ::1/128 drop            comment "loopback"
        ip6 daddr ::/128 drop             comment "unspecified"
        ip6 daddr ff00::/8 drop           comment "multicast"
        # Default: accept (public internet).
        accept
INNER
    elif [[ "$hosts" != "-" ]]; then
        # Specific hostname allowlist mode.
        IFS=',' read -ra hostarr <<< "$hosts"
        for h in "${hostarr[@]}"; do
            h_trimmed="${h//[[:space:]]/}"
            [[ -z "$h_trimmed" ]] && continue
            # Resolve the host to IPv4. IPv6 support is a future enhancement.
            mapfile -t ipv4s < <(getent ahostsv4 "$h_trimmed" 2>/dev/null | awk '{print $1}' | sort -u || true)
            if [[ ${#ipv4s[@]} -eq 0 ]]; then
                echo "        # WARNING: host ${h_trimmed} did not resolve at setup time"
                continue
            fi
            for ip in "${ipv4s[@]}"; do
                printf '        ip daddr %s accept comment "%s"\n' "$ip" "$h_trimmed"
            done
        done
        cat <<EOF
        # Default deny — anything else from this bridge is dropped.
        drop
EOF
    else
        # No-egress mode: nothing past the preamble (DNS, ICMP, established
        # — though ICMP/DNS to anywhere from a no-egress profile is mostly
        # academic, since ICMP/DNS to external IPs would still go through
        # forward and need somewhere to go; in practice the bridge's DHCP
        # resolver is the only DNS target reachable, which is fine).
        cat <<EOF
        # No egress.
        drop
EOF
    fi

    echo "    }"
done

echo "}"
} > "$NFT_FILE"

# Lint the ruleset before applying.
nft -c -f "$NFT_FILE"

# ---------------------------------------------------------------------------
# Apply: tear down any prior codeybox table, load the new one.
# ---------------------------------------------------------------------------
nft delete table inet codeybox 2>/dev/null || true
nft -f "$NFT_FILE"

# Persist via /etc/nftables.conf if present (Ubuntu's nftables.service path).
INCLUDE_FILE="/etc/nftables.conf"
if [[ -f "$INCLUDE_FILE" ]] && ! grep -qF "$NFT_FILE" "$INCLUDE_FILE"; then
    printf '\ninclude "%s"\n' "$NFT_FILE" >> "$INCLUDE_FILE"
fi
systemctl enable nftables.service >/dev/null 2>&1 || true

# Bring up bridges via systemd-networkd.
systemctl enable --now systemd-networkd >/dev/null
networkctl reload || true
# Each bridge needs an explicit reconfigure to come up.
for bridge in "${BRIDGES[@]}"; do
    networkctl reconfigure "$bridge" 2>/dev/null || true
done

# Install a loopback-only operator helper for graphical VNC access. The VNC
# server itself listens on the VM's cb-graphical address and allows only the
# host bridge gateway. This helper is the intended human-facing exposure path:
# it binds 127.0.0.1 on demand and proxies to one selected VM.
cat > "$VNC_HELPER" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat >&2 <<USAGE
Usage: codeybox-vnc-loopback <multipass-vm-name> [local-port]

Starts a foreground VNC proxy on 127.0.0.1:<local-port> for the selected
graphical Multipass VM. The remote VNC port defaults to 5900; override with
CODEYBOX_GRAPHICAL_VNC_PORT if the sandbox convention changes.
USAGE
}

if [[ $# -lt 1 || $# -gt 2 ]]; then
    usage
    exit 2
fi

for cmd in multipass systemd-socket-activate systemd-socket-proxyd; do
    command -v "$cmd" >/dev/null 2>&1 || { echo "missing required tool: $cmd" >&2; exit 1; }
done

vm="$1"
listen_port="${2:-5900}"
remote_port="${CODEYBOX_GRAPHICAL_VNC_PORT:-5900}"

if [[ ! "$listen_port" =~ ^[0-9]+$ || "$listen_port" -lt 1 || "$listen_port" -gt 65535 ]]; then
    echo "invalid local port: $listen_port" >&2
    exit 2
fi

addr="$(
    multipass exec "$vm" -- sh -lc 'ip -4 -o addr show | awk '"'"'/inet 10\.99\./{split($4,a,"/"); print a[1]; exit}'"'"'' |
        tr -d '\r' |
        head -n 1
)"

if [[ -z "$addr" ]]; then
    echo "VM '$vm' has no 10.99.x.x graphical/profile bridge address" >&2
    exit 1
fi

echo "Forwarding VNC: 127.0.0.1:${listen_port} -> ${addr}:${remote_port}" >&2
echo "Press Ctrl-C to stop." >&2
exec systemd-socket-activate -l "127.0.0.1:${listen_port}" --inetd -- systemd-socket-proxyd "${addr}:${remote_port}"
EOF
chmod 0755 "$VNC_HELPER"

# ---------------------------------------------------------------------------
# Done — summary.
# ---------------------------------------------------------------------------
echo
echo "✓ Created ${#NAMES[@]} sandbox network profile(s):"
for i in "${!NAMES[@]}"; do
    name="${NAMES[$i]}"
    bridge="${BRIDGES[$i]}"
    subnet="${SUBNETS[$i]}"
    hosts="${HOSTS[$i]}"
    printf '    %-12s  %-26s  %-15s  %s\n' "$name" "$bridge" "$subnet" "$hosts"
done
echo
echo "✓ nftables rules: $NFT_FILE"
echo "✓ Default Multipass interface (${MULTIPASS_DEFAULT_IFACE}) forwarding: blocked"
echo "✓ Graphical VNC loopback helper: $VNC_HELPER"
echo
echo "To verify:"
echo "  multipass networks                  # confirms bridges visible to multipass"
echo "  multipass launch --network <bridge> # launches VM on that profile"
echo "  nft list table inet codeybox        # inspects active rules"
echo "  codeybox-vnc-loopback <vm> 5901     # exposes one graphical VM on 127.0.0.1:5901"
echo
echo "Re-run this script after editing $CONFIG_FILE or to refresh resolved IPs."
