#!/usr/bin/env bash
#
# setup-host-networks.sh — operator-run setup for CodeyBox per-VM egress
# enforcement on Multipass-based sandboxes.
#
# What this does:
#   1. For each profile in the config file, creates a Linux bridge
#      (via systemd-networkd) with its own subnet and built-in DHCP server.
#   2. Writes nftables rules that:
#        - block all forward traffic on Multipass's default mpqemubr0
#          (so the VM's default NIC has no internet path)
#        - apply per-bridge allowlists (loopback, ESTABLISHED/RELATED, DNS,
#          and the resolved IPs of the configured allowed hosts; everything
#          else dropped)
#   3. Persists the rules so they survive reboot.
#
# Why: enforcement HAS to live on the host. An agent inside a VM with sudo
# can flush in-VM iptables, but it cannot touch the host's forward chain.
#
# Usage:
#   sudo /path/to/setup-host-networks.sh [config-file]
#
# If no config file is given, /etc/codeybox/networks.conf is used. Format:
# one profile per line, columns separated by whitespace —
#
#   # name           bridge          subnet         allowed-hosts
#   isolated         cb-iso          10.99.1.0/24   -
#   claude           cb-claude       10.99.2.0/24   api.anthropic.com
#   codex            cb-codex        10.99.3.0/24   api.openai.com
#   multi-llm        cb-multi-llm    10.99.4.0/24   api.anthropic.com,api.openai.com,api.githubcopilot.com
#
# allowed-hosts of "-" means no egress (fully isolated; only DNS + lo).
# Bridge names (column 2) must be ≤15 chars (Linux IFNAMSIZ limit).
# Profile names (column 1) have no length limit.
#
# Idempotent — re-run after editing the config or to refresh resolved IPs
# (useful when CDN endpoints rotate).

set -euo pipefail

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
    echo "must be run as root (try: sudo $0 $*)" >&2
    exit 1
fi

CONFIG_FILE="${1:-/etc/codeybox/networks.conf}"
NFT_FILE="/etc/nftables.d/codeybox.nft"
NETWORKD_DIR="/etc/systemd/network"
MULTIPASS_DEFAULT_IFACE="${CODEYBOX_MULTIPASS_DEFAULT_IFACE:-mpqemubr0}"

if [[ ! -r "$CONFIG_FILE" ]]; then
    cat >&2 <<EOF
config file $CONFIG_FILE not found.

Create it as: <name> <bridge> <subnet> <allowed-hosts-comma-sep-or-dash>

Example:
  # name           bridge          subnet         allowed-hosts
  isolated         cb-iso          10.99.1.0/24   -
  claude           cb-claude       10.99.2.0/24   api.anthropic.com

Then re-run: sudo $0 [path/to/config]
EOF
    exit 1
fi

# Sanity-check tooling.
for cmd in nft ip systemctl getent; do
    command -v "$cmd" >/dev/null 2>&1 || { echo "missing required tool: $cmd" >&2; exit 1; }
done
mkdir -p "$NETWORKD_DIR" "$(dirname "$NFT_FILE")"

# ---------------------------------------------------------------------------
# Parse the config file.
# ---------------------------------------------------------------------------
declare -a NAMES BRIDGES SUBNETS HOSTS
while IFS= read -r raw; do
    # Strip comments and surrounding whitespace.
    line="${raw%%#*}"
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" ]] && continue

    # Expect 4 whitespace-separated columns.
    read -r name bridge subnet hosts _rest <<< "$line"
    if [[ -z "$name" || -z "$bridge" || -z "$subnet" || -z "$hosts" ]]; then
        echo "invalid line: $raw" >&2; exit 1
    fi
    NAMES+=("$name"); BRIDGES+=("$bridge"); SUBNETS+=("$subnet"); HOSTS+=("$hosts")
done < "$CONFIG_FILE"

if [[ ${#NAMES[@]} -eq 0 ]]; then
    echo "no profiles in $CONFIG_FILE" >&2; exit 1
fi

# ---------------------------------------------------------------------------
# Per-profile systemd-networkd configuration: bridge + DHCPv4 server.
# ---------------------------------------------------------------------------
for i in "${!NAMES[@]}"; do
    bridge="${BRIDGES[$i]}"
    subnet="${SUBNETS[$i]}"
    network="${subnet%/*}"
    prefix="${subnet#*/}"
    # Gateway: x.y.z.1
    gw="$(awk -F. -v OFS=. '{print $1,$2,$3,1}' <<< "$network")"

    cat > "$NETWORKD_DIR/10-${bridge}.netdev" <<EOF
# Generated by codeybox setup-host-networks.sh — do not edit by hand.
[NetDev]
Name=${bridge}
Kind=bridge
EOF

    cat > "$NETWORKD_DIR/10-${bridge}.network" <<EOF
# Generated by codeybox setup-host-networks.sh — do not edit by hand.
[Match]
Name=${bridge}

[Network]
Address=${gw}/${prefix}
ConfigureWithoutCarrier=yes
DHCPServer=yes
IPMasquerade=ipv4

[DHCPServer]
PoolOffset=10
PoolSize=200
EmitDNS=yes
DNS=1.1.1.1
EOF
done

# ---------------------------------------------------------------------------
# Build the nftables ruleset.
# ---------------------------------------------------------------------------
ts="$(date -Iseconds)"

{
cat <<EOF
# Generated by codeybox setup-host-networks.sh at ${ts}.
# Do not edit by hand — re-run the script to regenerate.

table inet codeybox {
    chain forward {
        type filter hook forward priority -10; policy accept;

        # Multipass's default bridge — drop ALL forwarded traffic. The
        # multipass control plane uses INPUT (host -> guest), not FORWARD,
        # so this doesn't break VM management.
        iifname "${MULTIPASS_DEFAULT_IFACE}" jump cb-default-blocked
        oifname "${MULTIPASS_DEFAULT_IFACE}" jump cb-default-blocked
EOF

for i in "${!NAMES[@]}"; do
    name="${NAMES[$i]}"
    bridge="${BRIDGES[$i]}"
    echo "        iifname \"${bridge}\" jump cb-${name}"
done

cat <<EOF
    }

    chain cb-default-blocked {
        # Multipass's default mpqemubr0 has no useful internet path. Drop.
        drop
    }
EOF

for i in "${!NAMES[@]}"; do
    name="${NAMES[$i]}"
    hosts="${HOSTS[$i]}"

    cat <<EOF

    chain cb-${name} {
        # Standard "allow replies + DNS" preamble.
        ct state established,related accept
        ip protocol icmp accept
        udp dport 53 accept
        tcp dport 53 accept
EOF

    if [[ "$hosts" != "-" ]]; then
        IFS=',' read -ra hostarr <<< "$hosts"
        for h in "${hostarr[@]}"; do
            h_trimmed="${h//[[:space:]]/}"
            [[ -z "$h_trimmed" ]] && continue
            # Resolve the host to IPv4. IPv6 support is a future enhancement.
            mapfile -t ipv4s < <(getent ahostsv4 "$h_trimmed" 2>/dev/null | awk '{print $1}' | sort -u || true)
            if [[ ${#ipv4s[@]} -eq 0 ]]; then
                echo "        # WARNING: host ${h_trimmed} did not resolve at setup time"
                continue
            fi
            for ip in "${ipv4s[@]}"; do
                printf '        ip daddr %s accept comment "%s"\n' "$ip" "$h_trimmed"
            done
        done
    fi

    cat <<EOF
        # Default deny — anything else from this bridge is dropped.
        drop
    }
EOF
done

echo "}"
} > "$NFT_FILE"

# Lint the ruleset before applying.
nft -c -f "$NFT_FILE"

# ---------------------------------------------------------------------------
# Apply: tear down any prior codeybox table, load the new one.
# ---------------------------------------------------------------------------
nft delete table inet codeybox 2>/dev/null || true
nft -f "$NFT_FILE"

# Persist via /etc/nftables.conf if present (Ubuntu's nftables.service path).
INCLUDE_FILE="/etc/nftables.conf"
if [[ -f "$INCLUDE_FILE" ]] && ! grep -qF "$NFT_FILE" "$INCLUDE_FILE"; then
    printf '\ninclude "%s"\n' "$NFT_FILE" >> "$INCLUDE_FILE"
fi
systemctl enable nftables.service >/dev/null 2>&1 || true

# Bring up bridges via systemd-networkd.
systemctl enable --now systemd-networkd >/dev/null
networkctl reload || true
# Each bridge needs an explicit reconfigure to come up.
for bridge in "${BRIDGES[@]}"; do
    networkctl reconfigure "$bridge" 2>/dev/null || true
done

# ---------------------------------------------------------------------------
# Done — summary.
# ---------------------------------------------------------------------------
echo
echo "✓ Created ${#NAMES[@]} sandbox network profile(s):"
for i in "${!NAMES[@]}"; do
    name="${NAMES[$i]}"
    bridge="${BRIDGES[$i]}"
    subnet="${SUBNETS[$i]}"
    hosts="${HOSTS[$i]}"
    printf '    %-12s  %-26s  %-15s  %s\n' "$name" "$bridge" "$subnet" "$hosts"
done
echo
echo "✓ nftables rules: $NFT_FILE"
echo "✓ Default Multipass interface (${MULTIPASS_DEFAULT_IFACE}) forwarding: blocked"
echo
echo "To verify:"
echo "  multipass networks                  # confirms bridges visible to multipass"
echo "  multipass launch --network <bridge> # launches VM on that profile"
echo "  nft list table inet codeybox        # inspects active rules"
echo
echo "Re-run this script after editing $CONFIG_FILE or to refresh resolved IPs."
